services:
  html:
    image: asciidoctor/docker-asciidoctor:latest
    volumes:
      - "./document:/documents"
    command: make html
  pdf:
    image: asciidoctor/docker-asciidoctor:latest
    volumes:
      - "./document:/documents"
    command: make pdf
